/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>
#include "stm32f303xc.h"
#include "LaptopInterface.h"

void enableLEDs()
{
	RCC->AHBENR |= RCC_AHBENR_GPIOEEN;

	uint16_t *led_output_registers = ((uint16_t *)&(GPIOE->MODER)) + 1;
	*led_output_registers = 0x5555;
}

void toggleLEDs(uint8_t bitmap) {
	*(((uint8_t*)&(GPIOE->ODR)) + 1) = (*(((uint8_t*)&(GPIOE->ODR)) + 1)) ^ bitmap;
}


void stopGameTest() {
	toggleLEDs(0b11111111);
}

int main(void)
{
	enableLEDs();
	laptopInterfaceInitialise(&stopGameTest);
	setLaptopGreen();
	for(;;);
}
